# Generated by Django 3.0.4 on 2020-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='pics')),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
